version: "3.8"

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: promptaid
      POSTGRES_PASSWORD: promptaid
      POSTGRES_DB: promptaid
    ports:
      - "5434:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  minio:
    image: minio/minio:latest
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: promptaid
      MINIO_ROOT_PASSWORD: promptaid
      MINIO_DEFAULT_BUCKETS: promptaid
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    depends_on:
      - postgres


  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://promptaid:promptaid@postgres:5432/promptaid
      - S3_ENDPOINT=http://minio:9000  # Override for container networking
    depends_on:
      - postgres
      - minio
    volumes:
      - ./py_backend:/app
      - /app/__pycache__

volumes:
  pgdata:
  minio_data:
