environment: prod

image:
  name: SET-BY-CICD-IMAGE
  tag: SET-BY-CICD-TAG

resources:
  requests:
    cpu: "0.5"
    memory: "100Mi"
  limits:
    cpu: "1"
    memory: "100Mi"

ingress:
  host:

env:
  APP_TITLE: IFRC GO
  APP_ENVIRONMENT:
  APP_API_ENDPOINT:
  APP_MAPBOX_ACCESS_TOKEN:
  APP_TINY_API_KEY:
  APP_RISK_API_ENDPOINT:
  APP_SENTRY_DSN:
  APP_SDT_URL:
