apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ifrcgo-ui-storybook.fullname" . }}
  labels:
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "ifrcgo-ui-storybook.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ifrcgo-ui-storybook.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
