name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Configure git
        run: |
          git config user.name  "GitHub Actions"
          git config user.email "actions@github.com"
          git lfs install --local

      - name: Set vars
        run: |
          echo "HF_USERNAME=SCGR" >> $GITHUB_ENV
          echo "SPACE_NAME=Promptaid_Vision" >> $GITHUB_ENV

      - name: Check token & space reachability
        env:
          HF_API_KEY: ${{ secrets.HF_API_KEY }}
        run: |
          set -euo pipefail
          test -n "$HF_API_KEY" || (echo "Missing GitHub secret HF_API_KEY" && exit 1)
          echo "WHOAMI:"
          curl -sS -H "Authorization: Bearer $HF_API_KEY" https://huggingface.co/api/whoami-v2 || exit 1
          echo; echo "Check space URL:"
          curl -sS -o /dev/null -w "HTTP %{http_code}\n" \
            -H "Authorization: Bearer $HF_API_KEY" \
            https://huggingface.co/spaces/${HF_USERNAME}/${SPACE_NAME}

      - name: Test git auth to HF Space
        env:
          HF_API_KEY: ${{ secrets.HF_API_KEY }}
        run: |
          set -euo pipefail
          git ls-remote https://${HF_USERNAME}:${HF_API_KEY}@huggingface.co/spaces/${HF_USERNAME}/${SPACE_NAME}.git

      - name: Push to HF Space
        env:
          HF_API_KEY: ${{ secrets.HF_API_KEY }}
        run: |
          set -euo pipefail
          git remote remove space 2>/dev/null || true
          git remote add space https://${HF_USERNAME}:${HF_API_KEY}@huggingface.co/spaces/${HF_USERNAME}/${SPACE_NAME}.git
          git push space HEAD:main --force --verbose
